//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projet_Quiz_En_Ligne.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class TBLUserInfo
    {
        public int IdUs { get; set; }
        [Required(ErrorMessage ="champ requis")]
        [Display(Name="Nom")]
        public string UsernameUs { get; set; }
        [Required(ErrorMessage = "champ requis")]

        [Display(Name = "mdp")]
        public string PasswordUs { get; set; }

        [Display(Name = "RePassword")]
        [Required(ErrorMessage = "champ requis")]
        [DataType(DataType.Password)]
        [NotMapped]
        [Compare("PasswordUs", ErrorMessage = "Confirmer mot de passe")]
        public string RePasswordUs { get; set; }
    }
}
