// <auto-generated />
namespace Projet_Quiz_En_Ligne.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Modif1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Modif1));
        
        string IMigrationMetadata.Id
        {
            get { return "202112231553424_Modif1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
